# Since I do not know Pytorch yet, this entire file is also generated by ChatGPT. However, I got it to explain each line of code :D


import torch
import torch.nn as nn
from torchvision import models, transforms
from PIL import Image


# -----------------------------
# Device
# -----------------------------
device = torch.device(
    "cuda" if torch.cuda.is_available() else "cpu"
)


# -----------------------------
# Class Names
# IMPORTANT:
# Must match ImageFolder order
# -----------------------------
CLASS_NAMES = [
    "ai",
    "human"
]


# -----------------------------
# Image Transform
# Must match train.py
# -----------------------------
transform = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.ToTensor()
])


# -----------------------------
# Load Model
# -----------------------------
def load_model():

    model = models.resnet18(weights=None)

    model.fc = nn.Linear(
        model.fc.in_features,
        2
    )

    model.load_state_dict(
        torch.load(
            "detector.pth",
            map_location=device
        )
    )

    model.to(device)

    model.eval()

    return model


# Load once when file starts
model = load_model()


# -----------------------------
# Predict Function
# -----------------------------
def predict_image(image_path):

    image = Image.open(
        image_path
    ).convert("RGB")

    image = transform(image)

    image = image.unsqueeze(0)

    image = image.to(device)

    with torch.no_grad():

        outputs = model(image)

        probabilities = torch.softmax(
            outputs,
            dim=1
        )

        confidence, predicted = torch.max(
            probabilities,
            1
        )

    prediction = CLASS_NAMES[
        predicted.item()
    ]

    confidence = (
        confidence.item()
        * 100
    )

    return {
        "prediction": prediction,
        "confidence": round(
            confidence,
            2
        )
    }


# -----------------------------
# Testing
# -----------------------------
if __name__ == "__main__":

    image_path = input(
        "Image path: "
    )

    result = predict_image(
        image_path
    )

    print(
        f"Prediction: {result['prediction']}"
    )

    print(
        f"Confidence: {result['confidence']}%"
    )